###
GET S4H.dest/sap/opu/odata/sap/ZESK_EMP_ODATACRUD_SRV/ZEMP_LISTSet

###
GET S4H.dest/sap/opu/odata/sap/ZESK_EMP_ODATACRUD_SRV/ZEMP_LISTSet?$format=json
Accept: application/json

###
POST S4H.dest/sap/opu/odata/sap/ZESK_EMP_ODATACRUD_SRV/ZEMP_LISTSet
Content-Type: application/json
Accept: application/json

{
  "EmpId": 600,
  "EmpName": "RAVI",
  "EmpDept": "SAP",
  "EmpSalary": 46000
}

