
###
POST http://localhost:39991/odata/v4/POService/PurchaseOrderItems
Content-Type: application/json

{
  "ID": "ccccccc1-cccc-cccc-cccc-ccccccccccc1",
  "product": "Headphones",
  "quantity": 4,
  "price": 2500,
  "PO_ID": "33333333-3333-3333-3333-333333333333"
}
