@server=http://localhost:4004
@username=alice
@password=


### PurchaseOrder
# @name PurchaseOrder_GET
GET {{server}}/odata/v4/poservice/PurchaseOrder
Authorization: Basic {{username}}:{{password}}


### PurchaseOrder Drafts GET
# @name PurchaseOrder_Drafts_GET
GET {{server}}/odata/v4/poservice/PurchaseOrder?$filter=(IsActiveEntity eq false)
Authorization: Basic {{username}}:{{password}}


### PurchaseOrder Draft POST
# @name PurchaseOrder_Draft_POST
POST {{server}}/odata/v4/poservice/PurchaseOrder
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "poNumber": "poNumber-18762308",
  "supplier": "supplier-18762308",
  "status": "Draft",
  "totalAmount": 16637048.58,
  "to_poitems": [
    {
      "ID": "51411370-ea8e-48c2-83c6-d6228280fd03",
      "product": "product-5141137",
      "quantity": 66,
      "price": 1287039.88,
      "amount": 11170316.21,
      "createdAt": "2022-06-21T00:00:00.000Z",
      "createdBy": "createdBy.326xd@example.com",
      "modifiedAt": "2009-05-24T00:00:00.000Z",
      "modifiedBy": "modifiedBy.326xd@example.net"
    },
    {
      "ID": "5141138a-3db9-4150-9aa2-4634b493068a",
      "product": "product-5141138",
      "quantity": 51,
      "price": 20460540.24,
      "amount": 15706927.52,
      "createdAt": "2022-11-05T00:00:00.000Z",
      "createdBy": "createdBy.326xe@example.net",
      "modifiedAt": "2019-07-21T00:00:00.000Z",
      "modifiedBy": "modifiedBy.326xe@example.com"
    }
  ],
  "createdAt": "2005-07-04T00:00:00.000Z",
  "createdBy": "createdBy.b6538@example.com",
  "modifiedAt": "2023-01-31T00:00:00.000Z",
  "modifiedBy": "modifiedBy.b6538@example.com"
}


### Result from POST request above
@draftID={{PurchaseOrder_Draft_POST.response.body.$.ID}}


### PurchaseOrder Draft PATCH
# @name PurchaseOrder_Draft_Patch
PATCH {{server}}/odata/v4/poservice/PurchaseOrder(ID={{draftID}},IsActiveEntity=false)
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "poNumber": "poNumber-18762308",
  "supplier": "supplier-18762308",
  "status": "Draft",
  "totalAmount": 16637048.58,
  "to_poitems": [
    {
      "ID": "51411370-ea8e-48c2-83c6-d6228280fd03",
      "product": "product-5141137",
      "quantity": 66,
      "price": 1287039.88,
      "amount": 11170316.21,
      "createdAt": "2022-06-21T00:00:00.000Z",
      "createdBy": "createdBy.326xd@example.com",
      "modifiedAt": "2009-05-24T00:00:00.000Z",
      "modifiedBy": "modifiedBy.326xd@example.net"
    },
    {
      "ID": "5141138a-3db9-4150-9aa2-4634b493068a",
      "product": "product-5141138",
      "quantity": 51,
      "price": 20460540.24,
      "amount": 15706927.52,
      "createdAt": "2022-11-05T00:00:00.000Z",
      "createdBy": "createdBy.326xe@example.net",
      "modifiedAt": "2019-07-21T00:00:00.000Z",
      "modifiedBy": "modifiedBy.326xe@example.com"
    }
  ],
  "createdAt": "2005-07-04T00:00:00.000Z",
  "createdBy": "createdBy.b6538@example.com",
  "modifiedAt": "2023-01-31T00:00:00.000Z",
  "modifiedBy": "modifiedBy.b6538@example.com"
}


### PurchaseOrder Draft Prepare
# @name PurchaseOrder_Draft_Prepare
POST {{server}}/odata/v4/poservice/PurchaseOrder(ID={{draftID}},IsActiveEntity=false)/poservice.draftPrepare
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{}


### PurchaseOrder Draft Activate
# @name PurchaseOrder_Draft_Activate
POST {{server}}/odata/v4/poservice/PurchaseOrder(ID={{draftID}},IsActiveEntity=false)/poservice.draftActivate
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{}


### PurchaseOrderItems
# @name PurchaseOrderItems_GET
GET {{server}}/odata/v4/poservice/PurchaseOrderItems
Authorization: Basic {{username}}:{{password}}


### PurchaseOrderItems
# @name PurchaseOrderItems_POST
POST {{server}}/odata/v4/poservice/PurchaseOrderItems
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "51411370-ea8e-48c2-83c6-d6228280fd03",
  "product": "product-5141137",
  "quantity": 66,
  "price": 1287039.88,
  "amount": 11170316.21,
  "createdAt": "2022-06-21T00:00:00.000Z",
  "createdBy": "createdBy.326xd@example.com",
  "modifiedAt": "2009-05-24T00:00:00.000Z",
  "modifiedBy": "modifiedBy.326xd@example.net"
}


### PurchaseOrderItems
# @name PurchaseOrderItems_PATCH
PATCH {{server}}/odata/v4/poservice/PurchaseOrderItems/51411370-ea8e-48c2-83c6-d6228280fd03
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "51411370-ea8e-48c2-83c6-d6228280fd03",
  "product": "product-5141137",
  "quantity": 66,
  "price": 1287039.88,
  "amount": 11170316.21,
  "createdAt": "2022-06-21T00:00:00.000Z",
  "createdBy": "createdBy.326xd@example.com",
  "modifiedAt": "2009-05-24T00:00:00.000Z",
  "modifiedBy": "modifiedBy.326xd@example.net"
}


### PurchaseOrderItems
# @name PurchaseOrderItems_DELETE
DELETE {{server}}/odata/v4/poservice/PurchaseOrderItems/51411370-ea8e-48c2-83c6-d6228280fd03
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
